apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent-headless
  labels:
    app.kubernetes.io/name: zabbix-stress-agent
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: zabbix-stress-agent
  ports:
    - port: 10050
      name: zabbix-agent
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-agent
  labels:
    app.kubernetes.io/name: zabbix-stress-agent
spec:
  serviceName: zabbix-agent-headless
  replicas: {{ .Values.agentCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: zabbix-stress-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zabbix-stress-agent
    spec:
      containers:
        - name: zabbix-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              ORDINAL=${HOSTNAME##*-}
              export ZBX_LISTENPORT=$(({{ .Values.nodePortStart }} + ORDINAL))
              exec /usr/bin/docker-entrypoint.sh /usr/sbin/zabbix_agentd --foreground -c /etc/zabbix/zabbix_agentd.conf
          ports:
            - containerPort: {{ .Values.nodePortStart }}
              name: zabbix-agent
              protocol: TCP
          env:
            - name: ZBX_SERVER_HOST
              value: {{ .Values.zabbix.serverHost | quote }}
            - name: ZBX_METADATA
              value: {{ .Values.zabbix.metadata | quote }}
            - name: ZBX_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- range $i := until (int .Values.agentCount) }}
{{- $nodePort := add (int $.Values.nodePortStart) $i }}
{{- $podName := printf "zabbix-agent-%d" $i }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $podName }}-np
  labels:
    app.kubernetes.io/name: zabbix-stress-agent
    app.kubernetes.io/instance: {{ $podName }}
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: {{ $podName }}
  ports:
    - port: {{ $nodePort }}
      targetPort: {{ $nodePort }}
      nodePort: {{ $nodePort }}
      protocol: TCP
      name: zabbix-agent
{{- end }}
