apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-agent
  labels:
    app.kubernetes.io/name: zabbix-stress-agent
spec:
  serviceName: zabbix-agent-headless
  replicas: {{ .Values.agentCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: zabbix-stress-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zabbix-stress-agent
    spec:
      serviceAccountName: zabbix-agent
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: zabbix-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              ORDINAL=${HOSTNAME##*-}
              export ZBX_LISTENPORT=$(({{ .Values.portStart }} + ORDINAL))
              exec /usr/bin/docker-entrypoint.sh /usr/sbin/zabbix_agentd --foreground -c /etc/zabbix/zabbix_agentd.conf
          env:
            - name: ZBX_SERVER_HOST
              value: {{ .Values.zabbix.serverHost | quote }}
            - name: ZBX_METADATA
              value: {{ .Values.zabbix.metadata | quote }}
            - name: ZBX_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
